<?php

namespace Fup\UnividaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatosBasicosReunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosBasicosReunionRepository extends EntityRepository
{
}
