<?php

namespace Fup\UnividaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResponsablesActividadesReunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsablesActividadesReunionRepository extends EntityRepository
{
}
