fup_univida_homepage:
    pattern:  /hola
    defaults: { _controller: FupUnividaBundle:Default:index }

fup_univida_actas_reunion:
    pattern:  /actas/reunion
    defaults: { _controller: FupUnividaBundle:ActasReunion:cargarActasReunion }

fup_univida_nuevo_tipo_acta:
    pattern:  /actas/nuevotipo
    defaults: { _controller: FupUnividaBundle:Actas:nuevoTipoActa }
