fup_univida_homepage:
    pattern:  /hola
    defaults: { _controller: FupUnividaBundle:Default:index }

fup_univida_actas_reunion:
    pattern:  /actas/reunion
    defaults: { _controller: FupUnividaBundle:ActasReunion:cargarActasReunion }

fup_univida_nuevo_tipo_acta:
    pattern:  /actas/nuevotipo
    defaults: { _controller: FupUnividaBundle:Actas:nuevoTipoActa }
    
fup_univida_nueva_acta_reunion:
    pattern:  /actas/reunion/nueva
    defaults: { _controller: FupUnividaBundle:ActasReunion:nuevaActaReunion }

fup_univida_datos_basicos_nueva_acta_reunion:
    pattern:  /actas/reunion/nueva/datosbasicos
    defaults: { _controller: FupUnividaBundle:ActasReunion:agregarDatosBasicosActaReunion }
    
fup_univida_asistentes_nueva_acta_reunion:
    pattern:  /actas/reunion/nueva/asistentes
    defaults: { _controller: FupUnividaBundle:ActasReunion:agregarAsistentesActaReunion }
    
fup_univida_items_orden_dia_nueva_acta_reunion:
    pattern:  /actas/reunion/nueva/ordendia
    defaults: { _controller: FupUnividaBundle:ActasReunion:agregarOrdenDiaActaReunion }
    
fup_univida_generalidades_nueva_acta_reunion:
    pattern:  /actas/reunion/nueva/generalidades
    defaults: { _controller: FupUnividaBundle:ActasReunion:agregarGeneralidadActaReunion }
    
fup_univida_conclusiones_nueva_acta_reunion:
    pattern:  /actas/reunion/nueva/conclusiones
    defaults: { _controller: FupUnividaBundle:ActasReunion:agregarConclusionActaReunion }
    
fup_univida_responsables_actividades_nueva_acta_reunion:
    pattern:  /actas/reunion/nueva/responsablesactividades
    defaults: { _controller: FupUnividaBundle:ActasReunion:agregarResponsableActividadActaReunion }
    
fup_univida_guardar_acta_reunion:
    pattern:  /actas/reunion/nueva/guardaracta
    defaults: { _controller: FupUnividaBundle:ActasReunion:guardarActaReunion }